#pragma once

// PROGMEM-resident HTML/CSS/JS blobs for WebServerService's human-facing
// pages. Split out from WebServerService.cpp so that file stays about route
// handlers, not frontend markup. `inline constexpr` (C++17) gives each array
// a single definition across translation units without a .cpp file.

namespace WebAssets {

// HTML is split into two static flash-resident blocks so the title can be
// injected in the middle without building a temporary String.
inline constexpr char kHtmlHead1[] =
    "<!DOCTYPE html><html><head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>";

inline constexpr char kHtmlHead2[] =
    " - NerdBox</title>"
    "<style>"
    ":root{--bg:#0f1419;--card:#1a2129;--line:#2a3441;--fg:#d8e0ea;--dim:#7a8794;--accent:#4fc3f7;}"
    "*{box-sizing:border-box;}"
    "body{background:var(--bg);color:var(--fg);font-family:'Segoe UI',Arial,sans-serif;"
    "margin:0;padding:0;line-height:1.6;}"
    ".bar{max-width:1200px;margin:0 auto;box-sizing:border-box;}"
    "header{background:var(--card);border-bottom:1px solid var(--line);}"
    "header .bar{padding:0.9rem 1.2rem;display:flex;align-items:baseline;"
    "justify-content:space-between;flex-wrap:wrap;gap:0.5rem;}"
    "header h1{margin:0;font-size:1.3rem;color:var(--accent);}"
    "header .meta{color:var(--dim);font-size:0.85rem;}"
    "nav{background:var(--card);border-bottom:1px solid var(--line);}"
    "nav .bar{padding:0.6rem 1.2rem;display:flex;gap:1rem;font-size:0.85rem;flex-wrap:wrap;}"
    "nav a{color:var(--dim);text-decoration:none;}"
    "nav a:hover{color:var(--accent);}"
    ".content{max-width:1200px;margin:0 auto;padding:1.2rem;}"
    "pre{background:var(--card);padding:1rem;border-radius:8px;overflow-x:auto;"
    "border:1px solid var(--line);font-family:Consolas,monospace;color:var(--fg);}"
    "table{border-collapse:collapse;width:100%;margin-top:0.5rem;font-size:0.9rem;}"
    "th,td{padding:0.4rem 0.6rem;border-bottom:1px solid var(--line);text-align:left;}"
    "th{color:var(--dim);font-weight:600;}"
    "code{background:var(--card);border:1px solid var(--line);border-radius:4px;"
    "padding:0.1rem 0.35rem;}"
    "</style></head>"
    "<body>"
    "<header><div class='bar'>"
    "<h1>NerdBox</h1>"
    "<div class='meta'>";

inline constexpr char kHtmlHead3[] =
    "</div>"
    "</div></header>"
    "<nav><div class='bar'>"
    "<a href='/'>Home</a>"
    "<a href='/app-info'>App Info</a>"
    "<a href='/system-info'>System Info</a>"
    "<a href='/logs'>Logs</a>"
    "<a href='/config'>Config</a>"
    "<a href='/api'>API</a>"
    "</div></nav>"
    "<div class='content'>";

inline constexpr char kHtmlFoot[] = "</div></body></html>";

// Dashboard — single dark-themed page served whole from flash (send via
// chunked sendContent, zero per-request heap for the shell itself). All
// dynamic values are pulled client-side from GET /api/status on a 2 s timer,
// so this literal never needs to change per request.
inline constexpr char kDashboardHtml[] =
    "<!DOCTYPE html><html><head>"
    "<meta charset='UTF-8'>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>NerdBox</title>"
    "<style>"
    ":root{--bg:#0f1419;--card:#1a2129;--line:#2a3441;--fg:#d8e0ea;--dim:#7a8794;"
    "--accent:#4fc3f7;--ok:#66bb6a;--warn:#ffa726;--bad:#ef5350;}"
    "*{box-sizing:border-box;}"
    "body{background:var(--bg);color:var(--fg);font-family:'Segoe UI',Arial,sans-serif;"
    "margin:0;padding:0;line-height:1.5;transition:opacity .3s;}"
    "body.offline{opacity:.45;}"
    ".bar{max-width:1200px;margin:0 auto;box-sizing:border-box;}"
    "header{background:var(--card);border-bottom:1px solid var(--line);}"
    "header .bar{padding:0.9rem 1.2rem;display:flex;align-items:baseline;"
    "justify-content:space-between;flex-wrap:wrap;gap:0.5rem;}"
    "header h1{margin:0;font-size:1.3rem;color:var(--accent);}"
    "header .meta{color:var(--dim);font-size:0.85rem;}"
    "header .meta b{color:var(--fg);}"
    "nav{background:var(--card);border-bottom:1px solid var(--line);}"
    "nav .bar{padding:0.6rem 1.2rem;display:flex;gap:1rem;font-size:0.85rem;flex-wrap:wrap;}"
    "nav a{color:var(--dim);text-decoration:none;}"
    "nav a:hover{color:var(--accent);}"
    ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));"
    "gap:1rem;padding:1.2rem;max-width:1200px;margin:0 auto;}"
    ".card{background:var(--card);border:1px solid var(--line);border-radius:8px;"
    "padding:1rem;}"
    ".card h2{margin:0 0 0.7rem;font-size:0.8rem;text-transform:uppercase;"
    "letter-spacing:0.05em;color:var(--dim);}"
    ".row{display:flex;justify-content:space-between;padding:0.2rem 0;font-size:0.92rem;}"
    ".row .k{color:var(--dim);}"
    ".row .v{font-variant-numeric:tabular-nums;}"
    ".v.ok{color:var(--ok);}.v.warn{color:var(--warn);}.v.bad{color:var(--bad);}"
    "canvas{width:100%;height:60px;margin-top:0.4rem;}"
    ".btns{display:flex;gap:0.6rem;flex-wrap:wrap;}"
    "button{background:var(--bg);color:var(--fg);border:1px solid var(--line);"
    "border-radius:6px;padding:0.5rem 0.9rem;cursor:pointer;font-size:0.85rem;}"
    "button:hover{border-color:var(--accent);color:var(--accent);}"
    "button.danger:hover{border-color:var(--bad);color:var(--bad);}"
    "</style></head><body>"
    "<header><div class='bar'><h1>NerdBox</h1>"
    "<div class='meta'>Screen: <b id='screenName'>-</b> &middot; "
    "Updated <b id='refreshAge'>-</b></div></div></header>"
    "<nav><div class='bar'><a href='/app-info'>App Info</a><a href='/system-info'>System Info</a>"
    "<a href='/logs'>Logs</a><a href='/config'>Config</a><a href='/api'>API</a></div></nav>"
    "<div class='grid'>"

    "<div class='card'><h2>Device</h2>"
    "<div class='row'><span class='k'>Uptime</span><span class='v' id='uptime'>-</span></div>"
    "<div class='row'><span class='k'>Free heap</span><span class='v' id='heapFree'>-</span></div>"
    "<div class='row'><span class='k'>Min free heap</span><span class='v' "
    "id='heapMin'>-</span></div>"
    "<div class='row'><span class='k'>Free PSRAM</span><span class='v' "
    "id='psramFree'>-</span></div>"
    "<div class='row'><span class='k'>CPU freq</span><span class='v' id='cpuMhz'>-</span></div>"
    "</div>"

    "<div class='card'><h2>Network</h2>"
    "<div class='row'><span class='k'>WiFi</span><span class='v' id='wifi'>-</span></div>"
    "<div class='row'><span class='k'>RSSI</span><span class='v' id='rssi'>-</span></div>"
    "<div class='row'><span class='k'>IP</span><span class='v' id='ip'>-</span></div>"
    "<div class='row'><span class='k'>Internet</span><span class='v' id='internet'>-</span></div>"
    "<div class='row'><span class='k'>Probes</span><span class='v' id='probes'>-</span></div>"
    "</div>"

    "<div class='card'><h2>PC metrics feed</h2>"
    "<div class='row'><span class='k'>Status</span><span class='v' id='pcStatus'>-</span></div>"
    "<div class='row'><span class='k'>Data age</span><span class='v' id='pcAge'>-</span></div>"
    "<div class='row'><span class='k'>Parse time</span><span class='v' id='parseMs'>-</span></div>"
    "<div class='row'><span class='k'>Fetch ok/fail</span>"
    "<span class='v'><span id='fetchOk'>-</span> / <span id='fetchFail'>-</span></span></div>"
    "<div class='row'><span class='k'>Last error</span><span class='v' "
    "id='lastError'>-</span></div>"
    "</div>"

    "<div class='card'><h2>Rendering</h2>"
    "<div class='row'><span class='k'>Avg draw time</span><span class='v' "
    "id='drawAvg'>-</span></div>"
    "<div class='row'><span class='k'>Widget FPS</span><span class='v' id='fps'>-</span></div>"
    "<canvas id='spark' width='300' height='60'></canvas>"
    "</div>"

    "<div class='card'><h2>Tasks</h2>"
    "<div class='row'><span class='k'>Screen stack free</span><span class='v' "
    "id='screenStack'>-</span></div>"
    "<div class='row'><span class='k'>Background stack free</span><span class='v' "
    "id='bgStack'>-</span></div>"
    "</div>"

    "<div class='card'><h2>Screen</h2><div class='btns'>"
    "<button id='btnMain'>Main</button>"
    "<button id='btnSettings'>Settings</button>"
    "<button id='btnGame'>Game</button>"
    "<button id='btnWeather'>Weather</button>"
    "</div></div>"

    "<div class='card'><h2>System</h2><div class='btns'>"
    "<button id='btnRestart' class='danger'>Restart</button>"
    "</div></div>"

    "</div>"
    "<script>"
    "const $=id=>document.getElementById(id);"
    "let lastOk=Date.now();"
    "function setLevel(el,level){el.classList.remove('ok','warn','bad');el.classList.add(level);}"
    "function drawSpark(times){"
    "const c=$('spark'),ctx=c.getContext('2d');const w=c.width,h=c.height;"
    "ctx.clearRect(0,0,w,h);if(!times||!times.length)return;"
    "const max=Math.max.apply(null,times.concat([1]));"
    "ctx.strokeStyle='#4fc3f7';ctx.lineWidth=2;ctx.beginPath();"
    "times.forEach(function(t,i){"
    "const x=i/((times.length-1)||1)*w,y=h-(t/max)*h;"
    "if(i===0){ctx.moveTo(x,y);}else{ctx.lineTo(x,y);}"
    "});ctx.stroke();"
    "}"
    "async function refresh(){"
    "try{"
    "const r=await fetch('/api/status',{cache:'no-store'});"
    "const d=await r.json();lastOk=Date.now();document.body.classList.remove('offline');"
    "$('screenName').textContent=d.ui.screen;"
    "$('uptime').textContent=d.app.uptime;"
    "$('heapFree').textContent=d.sys.heap_free.toLocaleString()+' B';"
    "setLevel($('heapFree'),d.sys.heap_free<50000?'bad':d.sys.heap_free<100000?'warn':'ok');"
    "$('heapMin').textContent=d.sys.heap_min.toLocaleString()+' B';"
    "$('psramFree').textContent=d.sys.psram_free.toLocaleString()+' B';"
    "$('cpuMhz').textContent=d.sys.cpu_mhz+' MHz';"
    "$('drawAvg').textContent=d.app.draw_avg_ms.toFixed(1)+' ms';"
    "$('fps').textContent=d.app.widget_fps.toFixed(1);"
    "$('parseMs').textContent=d.app.parse_ms+' ms';"
    "drawSpark(d.app.draw_times);"
    "$('wifi').textContent=d.net.wifi?'Connected':'Disconnected';"
    "setLevel($('wifi'),d.net.wifi?'ok':'bad');"
    "$('rssi').textContent=d.net.rssi+' dBm';"
    "$('ip').textContent=d.net.ip;"
    "$('internet').textContent=d.net.internet;"
    "setLevel($('internet'),d.net.internet==='OK'?'ok':d.net.internet==='DOWN'?'bad':'warn');"
    "$('probes').textContent=d.net.probes.map(function(p){return p?'\\u25cf':'\\u25cb';}).join(' "
    "');"
    "$('pcStatus').textContent=!d.pc.available?'Unavailable':(d.pc.fresh?'Fresh':'Stale');"
    "setLevel($('pcStatus'),!d.pc.available?'bad':(d.pc.fresh?'ok':'warn'));"
    "$('pcAge').textContent=d.pc.age_ms+' ms';"
    "$('fetchOk').textContent=d.pc.fetch_ok;"
    "$('fetchFail').textContent=d.pc.fetch_fail;"
    "$('lastError').textContent=d.pc.last_error&&d.pc.last_error.length?d.pc.last_error:'\\u2014';"
    "$('screenStack').textContent=d.tasks.screen_stack_free;"
    "$('bgStack').textContent=d.tasks.background_stack_free;"
    "}catch(e){document.body.classList.add('offline');}"
    "$('refreshAge').textContent=Math.round((Date.now()-lastOk)/1000)+'s ago';"
    "}"
    "async function post(path){await fetch(path,{method:'POST'});refresh();}"
    "$('btnMain').onclick=function(){post('/screen/main');};"
    "$('btnSettings').onclick=function(){post('/screen/settings');};"
    "$('btnGame').onclick=function(){post('/screen/game');};"
    "$('btnWeather').onclick=function(){post('/screen/weather');};"
    "$('btnRestart').onclick=function(){if(confirm('Restart device?'))post('/restart');};"
    "refresh();setInterval(refresh,2000);"
    "</script></body></html>";

}  // namespace WebAssets
